language: php
php:
- 7.1
install: composer install
script: ./vendor/bin/phing test
after_success: ./vendor/bin/phing report-to-coveralls
notifications:
  email:
    recipients:
      - bert@2dotstwice.be
